name: stattrak
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_map: ^6.2.1
  flutter_map_location_marker: ^8.1.0
  flutter_typeahead: ^4.3.6
  flutter_map_cancellable_tile_provider: ^2.0.0
  latlong2: ^0.9.1
  http: ^1.2.1
  provider: ^6.0.3
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.0
  path: ^1.8.3
  mime: ^1.0.4
  youtube_player_iframe: ^5.2.1
  youtube_player_flutter: ^9.1.1
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
#   - assets/config/.env
    - assets/icons/

  fonts:
    - family: RubikMonoOne
      fonts:
        - asset: assets/fonts/RubikMonoOne-Regular.ttf

    - family: DMMono
      fonts:
        - asset: assets/fonts/DMMono-Regular.ttf

    - family: Dangrek
      fonts:
        - asset: assets/fonts/Dangrek-Regular.ttf